import { chromium, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
const browser=await chromium.launch({channel:'chrome',headless:true})
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1})
const page=await context.newPage()
const errors=[];page.on('pageerror',e=>errors.push(e.message))
await page.goto('http://127.0.0.1:5178')
await page.getByRole('heading',{name:'A clearer picture of learning.'}).waitFor()
await page.screenshot({path:'/private/tmp/forma-desktop.png',fullPage:true})
const axe=await new AxeBuilder({page}).analyze()
console.log('A11Y',JSON.stringify(axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.slice(0,10).map(n=>({target:n.target,summary:n.failureSummary}))}))))
await page.getByRole('button',{name:'Students 20',exact:true}).click()
await page.getByRole('textbox',{name:'Search students'}).fill('Maya')
await page.getByRole('button',{name:/Maya Chen.*STU-1001/}).click()
await page.locator('tbody tr').first().waitFor()
await expect(page.locator('tbody tr')).toHaveCount(100)
console.log('History rows',await page.locator('tbody tr').count())
await page.screenshot({path:'/private/tmp/forma-student.png',fullPage:true})
await page.getByRole('button',{name:'Skill library 12'}).click()
await expect(page.locator('.skill-card')).toHaveCount(12)
console.log('Skills',await page.locator('.skill-card').count())
await page.getByRole('button',{name:/01.*Combining like terms/}).click()
console.log('Draft',await page.getByRole('textbox',{name:'Ask about your students'}).inputValue())
await page.getByRole('button',{name:'New conversation'}).click()
await page.setViewportSize({width:390,height:844})
await page.screenshot({path:'/private/tmp/forma-mobile.png',fullPage:true})
expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
console.log('Mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))
expect(errors).toEqual([])
expect(axe.violations).toEqual([])
console.log('Page errors',errors)
await browser.close()
