import { chromium, expect } from '@playwright/test'
const browser=await chromium.launch({channel:'chrome',headless:true})
const context=await browser.newContext({viewport:{width:1440,height:1000}})
const page=await context.newPage()
await page.goto('http://127.0.0.1:5178')
await page.getByRole('heading',{name:'A clearer picture of learning.'}).waitFor()
const started=Date.now()
if(process.env.FORMA_STUDENT_CHECK){
  await page.getByRole('combobox',{name:'Conversation student scope'}).selectOption('STU-1020')
  await page.getByRole('textbox',{name:'Ask about your students'}).fill('How is Julian Reed doing with fractions? Give exact correctness and one next step.')
  await page.getByRole('button',{name:'Send message'}).click()
}else{await page.getByRole('button',{name:/Look closer at a skill/}).click()}
await expect(page.locator('.message.assistant .markdown')).toBeVisible({timeout:390000})
console.log('First visible text seconds',(Date.now()-started)/1000)
await expect(page.getByRole('button',{name:'New conversation'})).toBeEnabled({timeout:390000})
console.log('Live response seconds',(Date.now()-started)/1000)
console.log('ANSWER',await page.locator('.message.assistant .markdown').innerText())
await page.locator('.sources summary').click()
await expect(page.locator('.retrieval-query')).toContainText(process.env.FORMA_STUDENT_CHECK?'Julian Reed':'combining like terms')
await page.locator('.source-list button').first().click()
await expect(page.getByRole('dialog')).toBeVisible()
console.log('Evidence dialog visible',await page.getByRole('dialog').innerText())
await page.getByRole('button',{name:'Close dialog'}).click()
await page.screenshot({path:'/private/tmp/forma-chat.png',fullPage:true})
await page.getByRole('button',{name:'New conversation'}).click()
await expect(page.getByRole('heading',{name:'A clearer picture of learning.'})).toBeVisible()
await context.route('**/api/chat/stream',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'The local model is unavailable. Start it with npm run model, then try again.'})}))
await page.getByRole('textbox',{name:'Ask about your students'}).fill('Test connection')
await page.getByRole('button',{name:'Send message'}).click()
await expect(page.getByRole('alert')).toContainText('unavailable')
console.log('Model offline error shown correctly')
await browser.close()
