import { chromium, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
const browser=await chromium.launch({channel:'chrome',headless:true})
try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}})
  const page=await context.newPage()
  const errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('http://127.0.0.1:5178')
  await page.getByRole('button',{name:'Students 20',exact:true}).click()
  await page.getByRole('textbox',{name:'Search students'}).fill('Julian')
  await page.getByRole('button',{name:/Julian Reed.*STU-1020/}).click()
  await expect(page.getByRole('columnheader',{name:'Time taken',exact:true})).toBeVisible()
  const response=await page.request.get('http://127.0.0.1:5178/api/students/STU-1020')
  const student=await response.json()
  await expect(page.locator('.time-summary')).toContainText(student.summary.avg_time_seconds.toFixed(1)+' s')
  await expect(page.locator('.session-duration')).toHaveCount(100)
  for(let i=0;i<3;i++)await expect(page.locator('.session-duration').nth(i)).toHaveAttribute('title',student.history[i].time_taken_seconds+' seconds')
  const violations=(await new AxeBuilder({page}).analyze()).violations
  expect(violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))).toEqual([])
  await page.screenshot({path:'/private/tmp/forma-time-student.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
  await page.getByRole('button',{name:'Learning assistant',exact:true}).click()
  await page.getByRole('button',{name:'Build an insight',exact:true}).click()
  await page.getByRole('combobox',{name:'Insight skill'}).selectOption('S06')
  const skill=student.skills.find(s=>s.id==='S06')
  await expect(page.locator('.insight-preview')).toContainText(`Average time per problem: ${skill.avg_time_seconds.toFixed(1)} seconds`)
  await page.getByRole('radio',{name:/Summary/}).check()
  await page.getByRole('textbox',{name:'Additional focus'}).fill('Report only the exact average time in seconds per fraction problem and the total seconds spent on fractions.')
  await expect(page.getByRole('button',{name:'Generate insight'})).toBeEnabled()
  const finished=page.waitForResponse('**/api/chat/stream')
  await page.getByRole('button',{name:'Generate insight'}).click()
  const stream=await (await finished).text()
  const frame=stream.split('\n\n').find(frame=>frame.startsWith('event: done'))
  expect(frame).toBeTruthy()
  const result=JSON.parse(frame.split('data: ')[1])
  expect(result.sources[0].data.summary.avg_time_seconds).toBe(skill.avg_time_seconds)
  expect(result.sources[0].data.summary.total_time_seconds).toBe(skill.total_time_seconds)
  await expect(page.getByRole('button',{name:'New conversation'})).toBeEnabled({timeout:390000})
  const answer=await page.locator('.message.assistant .markdown').innerText()
  console.log(JSON.stringify({average_seconds:skill.avg_time_seconds,total_seconds:skill.total_time_seconds,answer,metrics:result.metrics}))
  await page.locator('.sources summary').click()
  await page.getByRole('button',{name:/FILTERED Selected students/}).click()
  await expect(page.getByRole('dialog')).toContainText('avg_time_seconds')
  await expect(page.getByRole('dialog')).toContainText('total_time_seconds')
  expect(errors).toEqual([])
  console.log('Session timing, scoped averages, accessibility, mobile layout, live RAG context, and evidence viewer passed')
}finally{await browser.close()}
